name: Example workflow yml

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Package
      uses: bpicode/github-action-fpm@master
      with:
        fpm_args: './build'
        fpm_opts: '--debug -n consul_helper -v 0.0.1 -m help@mailinator.com --url https://google.com --description "a helper" --prefix /usr/local/bin -t rpm -s dir'
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: consul_helper
        path: consul_helper-0.0.1-1.x86_64.rpm
        retention-days: 10
